export const Images = {
    logo: require("./logo.png"),
    intro_house: require("./house-intro.jpeg"),
    product1: require("./product-1.jpeg"),
    product2: require("./product-2.jpeg"),
    product3: require("./product-3.jpeg"),
    product4: require("./product-4.jpeg"),
    vision1: require("./vision1.jpeg"),
    vision2: require("./vision2.jpeg"),
    service1: require("./service1.png"),
    service2: require("./service2.png"),
    service3: require("./service3.png"),
    service4: require("./service4.png"),
    need1: require("./need1.jpeg"),
    need2: require("./need2.jpeg"),
    dream1: require("./dream1.jpeg"),
    dream2: require("./dream2.jpeg"),
    dream3: require("./dream3.jpeg"),
} 