import Document, { Html, Head, Main, NextScript, DocumentContext, DocumentInitialProps } from "next/document";

class MyDocument extends Document {
    static async getInitialProps(
        ctx: DocumentContext
      ): Promise<DocumentInitialProps> {
        const initialProps = await Document.getInitialProps(ctx)
    
        return initialProps
      }

  render() {
    return (
      <Html lang="en">
        <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://themekit.strealstudio.com/dhalem/wp-content/uploads/sites/7/2022/06/favicon.png" />
        </Head>
        <body>
          <Main />
           <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;
