import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import {Header, Footer} from '../components/index'
import HomePage from './Features/Home/index';
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home – Dhalem</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://themekit.strealstudio.com/dhalem/wp-content/uploads/sites/7/2022/06/favicon.png" />
      </Head>
      <Header />
      <HomePage />
      <Footer />
    </>
  )
}

export default Home
